version: '3.8'

services:
  data-analyst-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DEBUG=false
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  logs:
